version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=iprwc_webshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: openjdk:21-jdk-alpine
    volumes:
      - ./jouw-spring-boot-app.jar:/app.jar
      - ./images:/images
    command: ["java", "-jar", "/app.jar"]
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/iprwc_webshop
      - DB_USER=postgres
      - DB_PASS=${DB_PASS}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  db_data: